const TEMP = {
  schema: {
    pixel_config: {
      pixel_version: "str",
      pixel_level: "str",
      mf_flag: "str",
      track_behaviour_duration: "int",
      viewability_criteria: "float",
    },
    ad_fraud_rules_config: {
      attribution_window_hours: "int",
      rules: {
        uaMismatch: {
          status: "bool",
          fraud_description: "str",
          fraud_category: "str",
          fraud_sub_category: "str",
          priority: "int",
          call_recommendation: ["High", "Medium", "Low"],
          risk_level: ["Green", "Yellow", "Red"],
        },
        deprecatedBrowser: {
          status: "bool",
          threshold_samsung_internet: "int",
          threshold_firefox: "int",
          threshold_safari: "int",
          threshold_yandex_browser: "int",
          threshold_opera: "int",
          threshold_miuibrowser: "int",
          threshold_edge: "int",
          threshold_chrome: "int",
          threshold_chrome_mobile_webview: "int",
          fraud_description: "str",
          fraud_category: "str",
          fraud_sub_category: "str",
          priority: "int",
          call_recommendation: ["High", "Medium", "Low"],
          risk_level: ["Green", "Yellow", "Red"],
        },
        deprecatedOs: {
          status: "bool",
          threshold_ios: "int",
          threshold_android: "int",
          threshold_windows: "str",
          threshold_mac_os_x: "float",
          fraud_description: "str",
          fraud_category: "str",
          fraud_sub_category: "str",
          priority: "int",
          call_recommendation: ["High", "Medium", "Low"],
          risk_level: ["Green", "Yellow", "Red"],
        },
        crawlerUserAgent: {
          status: "bool",
          fraud_description: "str",
          fraud_category: "str",
          fraud_sub_category: "str",
          priority: "int",
          call_recommendation: ["High", "Medium", "Low"],
          risk_level: ["Green", "Yellow", "Red"],
        },
        geo: {
          status: "bool",
          whitelisted_countries: "str",
          fraud_description: "str",
          fraud_category: "str",
          fraud_sub_category: "str",
          priority: "int",
          call_recommendation: ["High", "Medium", "Low"],
          risk_level: ["Green", "Yellow", "Red"],
        },
        vpn: {
          status: "bool",
          categories: "str",
          whitelisted_isp_list: "str",
          fraud_description: "str",
          fraud_category: "str",
          fraud_sub_category: "str",
          priority: "int",
          call_recommendation: ["High", "Medium", "Low"],
          risk_level: ["Green", "Yellow", "Red"],
        },
        blacklistedUserAgent: {
          status: "bool",
          fraud_description: "str",
          fraud_category: "str",
          fraud_sub_category: "str",
          priority: "int",
          call_recommendation: ["High", "Medium", "Low"],
          risk_level: ["Green", "Yellow", "Red"],
        },
      },
    },
  },
  config: {
    pixel_config: {
      pixel_version: "v6.1",
      pixel_level: "basic",
      mf_flag: "s2s",
      track_behaviour_duration: 300,
      viewability_criteria: 0.5,
    },
    ad_fraud_rules_config: {
      attribution_window_hours: 24,
      rules: {
        uaMismatch: {
          status: true,
          fraud_description: "mf_rule_ua_mismatch_fraud_check",
          fraud_category: "bot_fraud_desc",
          fraud_sub_category: "Imperceptible Window",
          priority: 7,
          call_recommendation: "Low",
          risk_level: "Red",
        },
        deprecatedBrowser: {
          status: true,
          threshold_samsung_internet: 9,
          threshold_firefox: 63,
          threshold_safari: 13,
          threshold_yandex_browser: 17,
          threshold_opera: 20,
          threshold_miuibrowser: 12,
          threshold_edge: 79,
          threshold_chrome: 69,
          threshold_chrome_mobile_webview: 60,
          fraud_description: "mf_rule_deprecated_browser_check",
          fraud_category: "bot_fraud_desc",
          fraud_sub_category: "Deprecated Browser",
          priority: 20,
          call_recommendation: "Low",
          risk_level: "Red",
        },
        deprecatedOs: {
          status: true,
          threshold_ios: 12,
          threshold_android: 7,
          threshold_windows: "XP,Vista,7",
          threshold_mac_os_x: 10.14,
          fraud_description: "mf_rule_deprecated_os_check",
          fraud_category: "bot_fraud_desc",
          fraud_sub_category: "Deprecated OS",
          priority: 21,
          call_recommendation: "Low",
          risk_level: "Red",
        },
        crawlerUserAgent: {
          status: true,
          fraud_description: "mf_rule_crawler_user_agent_check",
          fraud_category: "bot_fraud_desc",
          fraud_sub_category: "Device Spoofing",
          priority: 5,
          call_recommendation: "Low",
          risk_level: "Red",
        },
        geo: {
          status: true,
          whitelisted_countries: "IN",
          fraud_description: "mf_rule_geo_fraud_check",
          fraud_category: "ip_fraud_desc",
          fraud_sub_category: "Geo Fraud",
          priority: 1,
          call_recommendation: "Medium",
          risk_level: "Yellow",
        },
        vpn: {
          status: true,
          categories: "VPN,DCH",
          whitelisted_isp_list: "icloud,zscaler,netskope",
          fraud_description: "mf_rule_vpn_check",
          fraud_category: "ip_fraud_desc",
          fraud_sub_category: "VPN Proxy",
          priority: 23,
          call_recommendation: "Medium",
          risk_level: "Yellow",
        },
        blacklistedUserAgent: {
          status: true,
          fraud_description: "mf_rule_blacklisted_user_agent_check",
          fraud_category: "user_validation_desc",
          fraud_sub_category: "Blacklisted UA",
          priority: 4,
          call_recommendation: "Low",
          risk_level: "Red",
        },
      },
    },
  },
};

export default TEMP;
